### PR TITLE
Create Code of Conduct and Contributing guidelines

### PR DESCRIPTION
**Pull request by SrNightmare09**
add the repository's code of conduct and contributing guidelines 

- make sure to replace `<your-contact-method >` in `CODE_OF_CONDUCT.md` line 63 with your contact method

- make sure to replace [INSERT EMAIL ADDRESS] with your email address in `CONTRIBUTING.md` at line 76

### CODE REVIEW

**Review by brundabharadwaj — APPROVED** [review]

**Comment by brundabharadwaj** [comment]
@adarsh-dayanand , Kindly review PR on Code of Conduct

**Comment by SrNightmare09** [comment]
🤞

**Review by adarsh-dayanand — APPROVED** [review]

**Comment by brundabharadwaj** [comment]
Thanks a lot @SrNightmare09 🎉

**Comment by SrNightmare09** [comment]
thanks for the merge 🎉🎉 looking forward to contributing more

**Comment by SrNightmare09** [comment]
hey, make sure to replace [INSERT EMAIL ADDRESS] in `CONTRIBUTING.md` with your own!

**Comment by brundabharadwaj** [comment]
> hey, make sure to replace [INSERT EMAIL ADDRESS] in `CONTRIBUTING.md` with your own!

updated, Thanks!

**Comment by SrNightmare09** [comment]
> > hey, make sure to replace [INSERT EMAIL ADDRESS] in `CONTRIBUTING.md` with your own!
> 
> 
> 
> updated, Thanks!

Nice! make sure to replace <your-contact-method> in line 63 of `CODE_OF_CONDUCT.md` with your email as well, and you'll be set!

**Comment by adarsh-dayanand** [comment]
@SrNightmare09 cool, updated. Thanks 🙌

**Pull request merged**
